name: intake-tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask-labextension
  - fsspec
  - gcsfs
  - intake
  - intake-esm
  - intake-xarray
  - hvplot
  - jupyterlab>=3
  - python=3.8
  - rasterio
  - s3fs
  - datashader
